/** Plain-language phrasing beats raw action keys for anyone scanning this. */
export const PHRASING: Record<string, string> = {
  "user.login": "signed in",
  "user.login_failed": "failed to sign in",
  "user.logout": "signed out",
  "user.invited": "invited someone",
  "user.invite_accepted": "accepted an invitation",
  "user.created": "created an account",
  "user.deleted": "deleted an account",
  "user.updated": "changed a user",
  "user.permissions_changed": "changed a user's permissions",
  "user.password_reset": "reset a user's password",
  "site.created": "registered a site",
  "site.updated": "updated a site",
  "site.login_started": "began signing in to a site",
  "site.login_saved": "saved a sign-in for a site",
  "site.deleted": "removed a site",
  "session.started": "started a session",
  "session.resumed": "resumed a session",
  "session.stopped": "stopped a session",
  "session.shared": "shared a session",
  "session.approval": "answered an approval",
  "device.paired": "paired a device",
  "device.revoked": "revoked a device",
  "settings.updated": "changed the limits",
};
